name: Manage tag for v0
on:
  push:
    tags:
    - "v0+.[0-9]+.[0-9]+"
jobs:
  tag:
    name: Manage tag
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        ref: docker-action
    -
      uses: haya14busa/action-update-semver@7d2c558640ea49e798d46539536190aff8c18715 # v1.5.1
      with:
        major_version_tag_only: true
